name: Lint CI

on:
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm" # or 'pnpm' / 'yarn' depending on your project

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Run ESLint
      - name: Run ESLint
        run: npm run lint

      # 4️⃣ Run ESLint Fix
      - name: Run ESLint Fix
        run: npm run lint:fix

      # 4️⃣ Run Test
      - name: Run Test
        run: npm run test
